"use client";
import { FormEvent } from "react";
import { AppShell, ItemOptions, useComputed } from "@/components/app-shell";
import { useInventory } from "@/components/inventory-provider";
export default function ItemsPage() {
  const { state, addItem, deleteItem } = useInventory();
  const { metrics } = useComputed();
  function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const id = String(form.get("id") || "").trim().toUpperCase(); if (state.items.some((item) => item.id === id)) return alert("รหัสนี้มีอยู่แล้ว"); addItem({ id, name: String(form.get("name") || "").trim(), category: String(form.get("category") || "อุปกรณ์"), unit: String(form.get("unit") || "").trim(), openingStock: Number(form.get("openingStock") || 0), reorderPoint: Number(form.get("reorderPoint") || 0), price: Number(form.get("price") || 0), description: String(form.get("description") || "รายการที่เพิ่มใหม่") }); event.currentTarget.reset(); }
  return <AppShell><section className="panel"><div className="section-head"><div><h2 className="section-title">จัดการรายการสินค้า</h2></div></div><form className="form-card" onSubmit={onSubmit}><div className="compact-grid"><div className="field"><label>รหัส</label><input name="id" required /></div><div className="field"><label>ชื่อรายการ</label><input name="name" required /></div><div className="field"><label>ประเภท</label><select name="category"><option>อุปกรณ์</option><option>วัตถุดิบ</option></select></div><div className="field"><label>หน่วย</label><input name="unit" required /></div><div className="field"><label>สต๊อกตั้งต้น</label><input name="openingStock" type="number" min="0" defaultValue="0" required /></div><div className="field"><label>จุดสั่งซื้อ</label><input name="reorderPoint" type="number" min="0" defaultValue="0" required /></div><div className="field"><label>ราคาต่อหน่วย</label><input name="price" type="number" min="0" defaultValue="0" required /></div><div className="field"><label>คำอธิบาย</label><input name="description" /></div></div><button className="primary-button" type="submit">เพิ่มรายการ</button></form></section><section className="content-grid"><section className="panel"><ItemOptions /></section><section className="panel"><div className="table-wrap"><table><thead><tr><th>รหัส</th><th>ชื่อ</th><th>คงเหลือ</th><th>จัดการ</th></tr></thead><tbody>{metrics.map((m) => <tr key={m.item.id}><td>{m.item.id}</td><td>{m.item.name}</td><td>{m.currentStock} {m.item.unit}</td><td><button className="danger-button" onClick={() => { if (confirm(`ลบ ${m.item.name} หรือไม่`)) deleteItem(m.item.id); }}>ลบ</button></td></tr>)}</tbody></table></div></section></section></AppShell>;
}
